import Foundation

class DoubleSound {
    
    private var doubleSounds: [String]?
    
    // MARK: - Methods
    
    func getSoundCount() -> Int {
        guard let sounds = doubleSounds else {return 0}
        return sounds.count
    }
    
    func restrictListToPairsContainingAtLeastOneSoundFrom(
        consonants: [String],
        vowels: [String]) {
        
        if consonants.isEmpty && vowels.isEmpty {return}
        
        // loop through all pairs and add any for which both consonant and vowel are in allowedSounds
        doubleSounds = [String]()
        for key in DoubleSound.soundMap.keys {
            let (c, v) = Ipa.splitDoubleSound(str: key)
            if stringContainsItemFromList(str: c, list: consonants) ||
                stringContainsItemFromList(str: v, list: vowels) {
                doubleSounds!.append(key)
            }
        }
    }
    
    func restrictListToAllPairsContaining(ipa: String) {
        if ipa.isEmpty {return}
        
        if Ipa.isSpecial(ipa: ipa) {
            restrictListToSpecialSoundsContaining(ipa: ipa)
            return
        }
        
        let singleItemArray = [ipa]
        if Ipa.isConsonant(ipa: ipa) {
            restrictListToPairsContainingAtLeastOneSoundFrom(consonants: singleItemArray, vowels: [String]())
        } else {
            restrictListToPairsContainingAtLeastOneSoundFrom(consonants: [String](), vowels: singleItemArray)
        }
    }
    
    func restrictListToPairsContainingBothSoundsFrom(
        consonants: [String],
        vowels: [String]) {
        
        // Since every pair contains both a vowel and a consonant,
        // an exact match requires both to be present.
        if vowels.isEmpty || consonants.isEmpty {return}
        
        // loop through all pairs and add any for with both consonant and vowel are in allowedSounds
        doubleSounds = [String]()
        for key in DoubleSound.soundMap.keys {
            let (c, v) = Ipa.splitDoubleSound(str: key)
            if (stringContainsItemFromList(str: c, list: consonants) && stringContainsItemFromList(str: v, list: vowels)) {
                doubleSounds!.append(key)
            }
        }
    }
    
    private func restrictListToSpecialSoundsContaining(ipa: String) {
        doubleSounds = [String]()
        for key in DoubleSound.specialSoundMap.keys {
            if shouldInclude(specialSound: key, forIpa: ipa) {
                doubleSounds!.append(key)
            }
        }
    }
    
    private func shouldInclude(specialSound: String, forIpa ipa: String) -> Bool {
        if !specialSound.contains(ipa) {return false}
        if specialSound.contains(Ipa.flap_t) && ipa == Ipa.schwa {return false}
        return true
    }
    
    func includeAllSounds() {
        doubleSounds = Array(DoubleSound.soundMap.keys)
    }
    
    private func stringContainsItemFromList(str: String, list: [String]) -> Bool {
        for item in list {
            if item == str {return true}
        }
        return false
    }
    
    
    
    // MARK: - Methods
    
    func getRandomIpa() -> String {
        
        if doubleSounds == nil || doubleSounds?.count == 0 {
            includeAllSounds()
        }
        
        // get random integer (0 <= x < numberOfSounds)
        let index = Int(arc4random_uniform(UInt32(doubleSounds!.count)))
        
        // translate integer to ipa string
        return doubleSounds![index]
    }
    
    class func getSoundFileName(doubleSoundIpa: String) -> String? {
        if let value = DoubleSound.specialSoundMap[doubleSoundIpa] {
            return value
        }
        return DoubleSound.soundMap[doubleSoundIpa]
    }
    
    func getSounds() -> [String] {
        if doubleSounds == nil {
            includeAllSounds()
        }
        return doubleSounds!
    }
    
    private static let soundMap = [
        "pi": "double_p_i",
        "pɪ": "double_p_is",
        "peɪ": "double_p_ei",
        "pɛ": "double_p_e",
        "pæ": "double_p_ae",
        "pɑ": "double_p_a",
        "pɔ": "double_p_c",
        "poʊ": "double_p_ou",
        "pʊ": "double_p_us",
        "pu": "double_p_u",
        "pʌ": "double_p_vu",
        "paɪ": "double_p_ai",
        "paʊ": "double_p_au",
        "pɔɪ": "double_p_oi",
        "pɝ": "double_p_ers",
        "pɑr": "double_p_ar",
        "pɛr": "double_p_er",
        "pɪr": "double_p_ir",
        "pɔr": "double_p_or",
        "bi": "double_b_i",
        "bɪ": "double_b_is",
        "beɪ": "double_b_ei",
        "bɛ": "double_b_e",
        "bæ": "double_b_ae",
        "bɑ": "double_b_a",
        "bɔ": "double_b_c",
        "boʊ": "double_b_ou",
        "bʊ": "double_b_us",
        "bu": "double_b_u",
        "bʌ": "double_b_vu",
        "baɪ": "double_b_ai",
        "baʊ": "double_b_au",
        "bɔɪ": "double_b_oi",
        "bɝ": "double_b_ers",
        "bɑr": "double_b_ar",
        "bɛr": "double_b_er",
        "bɪr": "double_b_ir",
        "bɔr": "double_b_or",
        "ti": "double_t_i",
        "tɪ": "double_t_is",
        "teɪ": "double_t_ei",
        "tɛ": "double_t_e",
        "tæ": "double_t_ae",
        "tɑ": "double_t_a",
        "tɔ": "double_t_c",
        "toʊ": "double_t_ou",
        "tʊ": "double_t_us",
        "tu": "double_t_u",
        "tʌ": "double_t_vu",
        "taɪ": "double_t_ai",
        "taʊ": "double_t_au",
        "tɔɪ": "double_t_oi",
        "tɝ": "double_t_ers",
        "tɑr": "double_t_ar",
        "tɛr": "double_t_er",
        "tɪr": "double_t_ir",
        "tɔr": "double_t_or",
        "di": "double_d_i",
        "dɪ": "double_d_is",
        "deɪ": "double_d_ei",
        "dɛ": "double_d_e",
        "dæ": "double_d_ae",
        "dɑ": "double_d_a",
        "dɔ": "double_d_c",
        "doʊ": "double_d_ou",
        "dʊ": "double_d_us",
        "du": "double_d_u",
        "dʌ": "double_d_vu",
        "daɪ": "double_d_ai",
        "daʊ": "double_d_au",
        "dɔɪ": "double_d_oi",
        "dɝ": "double_d_ers",
        "dɑr": "double_d_ar",
        "dɛr": "double_d_er",
        "dɪr": "double_d_ir",
        "dɔr": "double_d_or",
        "ki": "double_k_i",
        "kɪ": "double_k_is",
        "keɪ": "double_k_ei",
        "kɛ": "double_k_e",
        "kæ": "double_k_ae",
        "kɑ": "double_k_a",
        "kɔ": "double_k_c",
        "koʊ": "double_k_ou",
        "kʊ": "double_k_us",
        "ku": "double_k_u",
        "kʌ": "double_k_vu",
        "kaɪ": "double_k_ai",
        "kaʊ": "double_k_au",
        "kɔɪ": "double_k_oi",
        "kɝ": "double_k_ers",
        "kɑr": "double_k_ar",
        "kɛr": "double_k_er",
        "kɪr": "double_k_ir",
        "kɔr": "double_k_or",
        "gi": "double_g_i",
        "gɪ": "double_g_is",
        "geɪ": "double_g_ei",
        "gɛ": "double_g_e",
        "gæ": "double_g_ae",
        "gɑ": "double_g_a",
        "gɔ": "double_g_c",
        "goʊ": "double_g_ou",
        "gʊ": "double_g_us",
        "gu": "double_g_u",
        "gʌ": "double_g_vu",
        "gaɪ": "double_g_ai",
        "gaʊ": "double_g_au",
        "gɔɪ": "double_g_oi",
        "gɝ": "double_g_ers",
        "gɑr": "double_g_ar",
        "gɛr": "double_g_er",
        "gɪr": "double_g_ir",
        "gɔr": "double_g_or",
        "ʧi": "double_ch_i",
        "ʧɪ": "double_ch_is",
        "ʧeɪ": "double_ch_ei",
        "ʧɛ": "double_ch_e",
        "ʧæ": "double_ch_ae",
        "ʧɑ": "double_ch_a",
        "ʧɔ": "double_ch_c",
        "ʧoʊ": "double_ch_ou",
        "ʧʊ": "double_ch_us",
        "ʧu": "double_ch_u",
        "ʧʌ": "double_ch_vu",
        "ʧaɪ": "double_ch_ai",
        "ʧaʊ": "double_ch_au",
        "ʧɔɪ": "double_ch_oi",
        "ʧɝ": "double_ch_ers",
        "ʧɑr": "double_ch_ar",
        "ʧɛr": "double_ch_er",
        "ʧɪr": "double_ch_ir",
        "ʧɔr": "double_ch_or",
        "ʤi": "double_dzh_i",
        "ʤɪ": "double_dzh_is",
        "ʤeɪ": "double_dzh_ei",
        "ʤɛ": "double_dzh_e",
        "ʤæ": "double_dzh_ae",
        "ʤɑ": "double_dzh_a",
        "ʤɔ": "double_dzh_c",
        "ʤoʊ": "double_dzh_ou",
        "ʤʊ": "double_dzh_us",
        "ʤu": "double_dzh_u",
        "ʤʌ": "double_dzh_vu",
        "ʤaɪ": "double_dzh_ai",
        "ʤaʊ": "double_dzh_au",
        "ʤɔɪ": "double_dzh_oi",
        "ʤɝ": "double_dzh_ers",
        "ʤɑr": "double_dzh_ar",
        "ʤɛr": "double_dzh_er",
        "ʤɪr": "double_dzh_ir",
        "ʤɔr": "double_dzh_or",
        "fi": "double_f_i",
        "fɪ": "double_f_is",
        "feɪ": "double_f_ei",
        "fɛ": "double_f_e",
        "fæ": "double_f_ae",
        "fɑ": "double_f_a",
        "fɔ": "double_f_c",
        "foʊ": "double_f_ou",
        "fʊ": "double_f_us",
        "fu": "double_f_u",
        "fʌ": "double_f_vu",
        "faɪ": "double_f_ai",
        "faʊ": "double_f_au",
        "fɔɪ": "double_f_oi",
        "fɝ": "double_f_ers",
        "fɑr": "double_f_ar",
        "fɛr": "double_f_er",
        "fɪr": "double_f_ir",
        "fɔr": "double_f_or",
        "vi": "double_v_i",
        "vɪ": "double_v_is",
        "veɪ": "double_v_ei",
        "vɛ": "double_v_e",
        "væ": "double_v_ae",
        "vɑ": "double_v_a",
        "vɔ": "double_v_c",
        "voʊ": "double_v_ou",
        "vʊ": "double_v_us",
        "vu": "double_v_u",
        "vʌ": "double_v_vu",
        "vaɪ": "double_v_ai",
        "vaʊ": "double_v_au",
        "vɔɪ": "double_v_oi",
        "vɝ": "double_v_ers",
        "vɑr": "double_v_ar",
        "vɛr": "double_v_er",
        "vɪr": "double_v_ir",
        "vɔr": "double_v_or",
        "θi": "double_th_i",
        "θɪ": "double_th_is",
        "θeɪ": "double_th_ei",
        "θɛ": "double_th_e",
        "θæ": "double_th_ae",
        "θɑ": "double_th_a",
        "θɔ": "double_th_c",
        "θoʊ": "double_th_ou",
        "θʊ": "double_th_us",
        "θu": "double_th_u",
        "θʌ": "double_th_vu",
        "θaɪ": "double_th_ai",
        "θaʊ": "double_th_au",
        "θɔɪ": "double_th_oi",
        "θɝ": "double_th_ers",
        "θɑr": "double_th_ar",
        "θɛr": "double_th_er",
        "θɪr": "double_th_ir",
        "θɔr": "double_th_or",
        "ði": "double_thv_i",
        "ðɪ": "double_thv_is",
        "ðeɪ": "double_thv_ei",
        "ðɛ": "double_thv_e",
        "ðæ": "double_thv_ae",
        "ðɑ": "double_thv_a",
        "ðɔ": "double_thv_c",
        "ðoʊ": "double_thv_ou",
        "ðʊ": "double_thv_us",
        "ðu": "double_thv_u",
        "ðʌ": "double_thv_vu",
        "ðaɪ": "double_thv_ai",
        "ðaʊ": "double_thv_au",
        "ðɔɪ": "double_thv_oi",
        "ðɝ": "double_thv_ers",
        "ðɑr": "double_thv_ar",
        "ðɛr": "double_thv_er",
        "ðɪr": "double_thv_ir",
        "ðɔr": "double_thv_or",
        "si": "double_s_i",
        "sɪ": "double_s_is",
        "seɪ": "double_s_ei",
        "sɛ": "double_s_e",
        "sæ": "double_s_ae",
        "sɑ": "double_s_a",
        "sɔ": "double_s_c",
        "soʊ": "double_s_ou",
        "sʊ": "double_s_us",
        "su": "double_s_u",
        "sʌ": "double_s_vu",
        "saɪ": "double_s_ai",
        "saʊ": "double_s_au",
        "sɔɪ": "double_s_oi",
        "sɝ": "double_s_ers",
        "sɑr": "double_s_ar",
        "sɛr": "double_s_er",
        "sɪr": "double_s_ir",
        "sɔr": "double_s_or",
        "zi": "double_z_i",
        "zɪ": "double_z_is",
        "zeɪ": "double_z_ei",
        "zɛ": "double_z_e",
        "zæ": "double_z_ae",
        "zɑ": "double_z_a",
        "zɔ": "double_z_c",
        "zoʊ": "double_z_ou",
        "zʊ": "double_z_us",
        "zu": "double_z_u",
        "zʌ": "double_z_vu",
        "zaɪ": "double_z_ai",
        "zaʊ": "double_z_au",
        "zɔɪ": "double_z_oi",
        "zɝ": "double_z_ers",
        "zɑr": "double_z_ar",
        "zɛr": "double_z_er",
        "zɪr": "double_z_ir",
        "zɔr": "double_z_or",
        "ʃi": "double_sh_i",
        "ʃɪ": "double_sh_is",
        "ʃeɪ": "double_sh_ei",
        "ʃɛ": "double_sh_e",
        "ʃæ": "double_sh_ae",
        "ʃɑ": "double_sh_a",
        "ʃɔ": "double_sh_c",
        "ʃoʊ": "double_sh_ou",
        "ʃʊ": "double_sh_us",
        "ʃu": "double_sh_u",
        "ʃʌ": "double_sh_vu",
        "ʃaɪ": "double_sh_ai",
        "ʃaʊ": "double_sh_au",
        "ʃɔɪ": "double_sh_oi",
        "ʃɝ": "double_sh_ers",
        "ʃɑr": "double_sh_ar",
        "ʃɛr": "double_sh_er",
        "ʃɪr": "double_sh_ir",
        "ʃɔr": "double_sh_or",
        "ʒi": "double_zh_i",
        "ʒɪ": "double_zh_is",
        "ʒeɪ": "double_zh_ei",
        "ʒɛ": "double_zh_e",
        "ʒæ": "double_zh_ae",
        "ʒɑ": "double_zh_a",
        "ʒɔ": "double_zh_c",
        "ʒoʊ": "double_zh_ou",
        "ʒʊ": "double_zh_us",
        "ʒu": "double_zh_u",
        "ʒʌ": "double_zh_vu",
        "ʒaɪ": "double_zh_ai",
        "ʒaʊ": "double_zh_au",
        "ʒɔɪ": "double_zh_oi",
        "ʒɝ": "double_zh_ers",
        "ʒɑr": "double_zh_ar",
        "ʒɛr": "double_zh_er",
        "ʒɪr": "double_zh_ir",
        "ʒɔr": "double_zh_or",
        "mi": "double_m_i",
        "mɪ": "double_m_is",
        "meɪ": "double_m_ei",
        "mɛ": "double_m_e",
        "mæ": "double_m_ae",
        "mɑ": "double_m_a",
        "mɔ": "double_m_c",
        "moʊ": "double_m_ou",
        "mʊ": "double_m_us",
        "mu": "double_m_u",
        "mʌ": "double_m_vu",
        "maɪ": "double_m_ai",
        "maʊ": "double_m_au",
        "mɔɪ": "double_m_oi",
        "mɝ": "double_m_ers",
        "mɑr": "double_m_ar",
        "mɛr": "double_m_er",
        "mɪr": "double_m_ir",
        "mɔr": "double_m_or",
        "ni": "double_n_i",
        "nɪ": "double_n_is",
        "neɪ": "double_n_ei",
        "nɛ": "double_n_e",
        "næ": "double_n_ae",
        "nɑ": "double_n_a",
        "nɔ": "double_n_c",
        "noʊ": "double_n_ou",
        "nʊ": "double_n_us",
        "nu": "double_n_u",
        "nʌ": "double_n_vu",
        "naɪ": "double_n_ai",
        "naʊ": "double_n_au",
        "nɔɪ": "double_n_oi",
        "nɝ": "double_n_ers",
        "nɑr": "double_n_ar",
        "nɛr": "double_n_er",
        "nɪr": "double_n_ir",
        "nɔr": "double_n_or",
        "li": "double_l_i",
        "lɪ": "double_l_is",
        "leɪ": "double_l_ei",
        "lɛ": "double_l_e",
        "læ": "double_l_ae",
        "lɑ": "double_l_a",
        "lɔ": "double_l_c",
        "loʊ": "double_l_ou",
        "lʊ": "double_l_us",
        "lu": "double_l_u",
        "lʌ": "double_l_vu",
        "laɪ": "double_l_ai",
        "laʊ": "double_l_au",
        "lɔɪ": "double_l_oi",
        "lɝ": "double_l_ers",
        "lɑr": "double_l_ar",
        "lɛr": "double_l_er",
        "lɪr": "double_l_ir",
        "lɔr": "double_l_or",
        "wi": "double_w_i",
        "wɪ": "double_w_is",
        "weɪ": "double_w_ei",
        "wɛ": "double_w_e",
        "wæ": "double_w_ae",
        "wɑ": "double_w_a",
        "wɔ": "double_w_c",
        "woʊ": "double_w_ou",
        "wʊ": "double_w_us",
        "wu": "double_w_u",
        "wʌ": "double_w_vu",
        "waɪ": "double_w_ai",
        "waʊ": "double_w_au",
        "wɔɪ": "double_w_oi",
        "wɝ": "double_w_ers",
        "wɑr": "double_w_ar",
        "wɛr": "double_w_er",
        "wɪr": "double_w_ir",
        "wɔr": "double_w_or",
        "ji": "double_j_i",
        "jɪ": "double_j_is",
        "jeɪ": "double_j_ei",
        "jɛ": "double_j_e",
        "jæ": "double_j_ae",
        "jɑ": "double_j_a",
        "jɔ": "double_j_c",
        "joʊ": "double_j_ou",
        "jʊ": "double_j_us",
        "ju": "double_j_u",
        "jʌ": "double_j_vu",
        "jaɪ": "double_j_ai",
        "jaʊ": "double_j_au",
        "jɔɪ": "double_j_oi",
        "jɝ": "double_j_ers",
        "jɑr": "double_j_ar",
        "jɛr": "double_j_er",
        "jɪr": "double_j_ir",
        "jɔr": "double_j_or",
        "hi": "double_h_i",
        "hɪ": "double_h_is",
        "heɪ": "double_h_ei",
        "hɛ": "double_h_e",
        "hæ": "double_h_ae",
        "hɑ": "double_h_a",
        "hɔ": "double_h_c",
        "hoʊ": "double_h_ou",
        "hʊ": "double_h_us",
        "hu": "double_h_u",
        "hʌ": "double_h_vu",
        "haɪ": "double_h_ai",
        "haʊ": "double_h_au",
        "hɔɪ": "double_h_oi",
        "hɝ": "double_h_ers",
        "hɑr": "double_h_ar",
        "hɛr": "double_h_er",
        "hɪr": "double_h_ir",
        "hɔr": "double_h_or",
        "ri": "double_r_i",
        "rɪ": "double_r_is",
        "reɪ": "double_r_ei",
        "rɛ": "double_r_e",
        "ræ": "double_r_ae",
        "rɑ": "double_r_a",
        "rɔ": "double_r_c",
        "roʊ": "double_r_ou",
        "rʊ": "double_r_us",
        "ru": "double_r_u",
        "rʌ": "double_r_vu",
        "raɪ": "double_r_ai",
        "raʊ": "double_r_au",
        "rɔɪ": "double_r_oi",
        "rɝ": "double_r_ers",
        "rɑr": "double_r_ar",
        "rɛr": "double_r_er",
        "rɪr": "double_r_ir",
        "rɔr": "double_r_or",
        "ip": "double_i_p",
        "ɪp": "double_is_p",
        "eɪp": "double_ei_p",
        "ɛp": "double_e_p",
        "æp": "double_ae_p",
        "ɑp": "double_a_p",
        "ɔp": "double_c_p",
        "oʊp": "double_ou_p",
        "ʊp": "double_us_p",
        "up": "double_u_p",
        "ʌp": "double_vu_p",
        "aɪp": "double_ai_p",
        "aʊp": "double_au_p",
        "ɔɪp": "double_oi_p",
        "ɝp": "double_ers_p",
        "ɑrp": "double_ar_p",
        "ɛrp": "double_er_p",
        "ɪrp": "double_ir_p",
        "ɔrp": "double_or_p",
        "ib": "double_i_b",
        "ɪb": "double_is_b",
        "eɪb": "double_ei_b",
        "ɛb": "double_e_b",
        "æb": "double_ae_b",
        "ɑb": "double_a_b",
        "ɔb": "double_c_b",
        "oʊb": "double_ou_b",
        "ʊb": "double_us_b",
        "ub": "double_u_b",
        "ʌb": "double_vu_b",
        "aɪb": "double_ai_b",
        "aʊb": "double_au_b",
        "ɔɪb": "double_oi_b",
        "ɝb": "double_ers_b",
        "ɑrb": "double_ar_b",
        "ɛrb": "double_er_b",
        "ɪrb": "double_ir_b",
        "ɔrb": "double_or_b",
        "it": "double_i_t",
        "ɪt": "double_is_t",
        "eɪt": "double_ei_t",
        "ɛt": "double_e_t",
        "æt": "double_ae_t",
        "ɑt": "double_a_t",
        "ɔt": "double_c_t",
        "oʊt": "double_ou_t",
        "ʊt": "double_us_t",
        "ut": "double_u_t",
        "ʌt": "double_vu_t",
        "aɪt": "double_ai_t",
        "aʊt": "double_au_t",
        "ɔɪt": "double_oi_t",
        "ɝt": "double_ers_t",
        "ɑrt": "double_ar_t",
        "ɛrt": "double_er_t",
        "ɪrt": "double_ir_t",
        "ɔrt": "double_or_t",
        "id": "double_i_d",
        "ɪd": "double_is_d",
        "eɪd": "double_ei_d",
        "ɛd": "double_e_d",
        "æd": "double_ae_d",
        "ɑd": "double_a_d",
        "ɔd": "double_c_d",
        "oʊd": "double_ou_d",
        "ʊd": "double_us_d",
        "ud": "double_u_d",
        "ʌd": "double_vu_d",
        "aɪd": "double_ai_d",
        "aʊd": "double_au_d",
        "ɔɪd": "double_oi_d",
        "ɝd": "double_ers_d",
        "ɑrd": "double_ar_d",
        "ɛrd": "double_er_d",
        "ɪrd": "double_ir_d",
        "ɔrd": "double_or_d",
        "ik": "double_i_k",
        "ɪk": "double_is_k",
        "eɪk": "double_ei_k",
        "ɛk": "double_e_k",
        "æk": "double_ae_k",
        "ɑk": "double_a_k",
        "ɔk": "double_c_k",
        "oʊk": "double_ou_k",
        "ʊk": "double_us_k",
        "uk": "double_u_k",
        "ʌk": "double_vu_k",
        "aɪk": "double_ai_k",
        "aʊk": "double_au_k",
        "ɔɪk": "double_oi_k",
        "ɝk": "double_ers_k",
        "ɑrk": "double_ar_k",
        "ɛrk": "double_er_k",
        "ɪrk": "double_ir_k",
        "ɔrk": "double_or_k",
        "ig": "double_i_g",
        "ɪg": "double_is_g",
        "eɪg": "double_ei_g",
        "ɛg": "double_e_g",
        "æg": "double_ae_g",
        "ɑg": "double_a_g",
        "ɔg": "double_c_g",
        "oʊg": "double_ou_g",
        "ʊg": "double_us_g",
        "ug": "double_u_g",
        "ʌg": "double_vu_g",
        "aɪg": "double_ai_g",
        "aʊg": "double_au_g",
        "ɔɪg": "double_oi_g",
        "ɝg": "double_ers_g",
        "ɑrg": "double_ar_g",
        "ɛrg": "double_er_g",
        "ɪrg": "double_ir_g",
        "ɔrg": "double_or_g",
        "iʧ": "double_i_ch",
        "ɪʧ": "double_is_ch",
        "eɪʧ": "double_ei_ch",
        "ɛʧ": "double_e_ch",
        "æʧ": "double_ae_ch",
        "ɑʧ": "double_a_ch",
        "ɔʧ": "double_c_ch",
        "oʊʧ": "double_ou_ch",
        "ʊʧ": "double_us_ch",
        "uʧ": "double_u_ch",
        "ʌʧ": "double_vu_ch",
        "aɪʧ": "double_ai_ch",
        "aʊʧ": "double_au_ch",
        "ɔɪʧ": "double_oi_ch",
        "ɝʧ": "double_ers_ch",
        "ɑrʧ": "double_ar_ch",
        "ɛrʧ": "double_er_ch",
        "ɪrʧ": "double_ir_ch",
        "ɔrʧ": "double_or_ch",
        "iʤ": "double_i_dzh",
        "ɪʤ": "double_is_dzh",
        "eɪʤ": "double_ei_dzh",
        "ɛʤ": "double_e_dzh",
        "æʤ": "double_ae_dzh",
        "ɑʤ": "double_a_dzh",
        "ɔʤ": "double_c_dzh",
        "oʊʤ": "double_ou_dzh",
        "ʊʤ": "double_us_dzh",
        "uʤ": "double_u_dzh",
        "ʌʤ": "double_vu_dzh",
        "aɪʤ": "double_ai_dzh",
        "aʊʤ": "double_au_dzh",
        "ɔɪʤ": "double_oi_dzh",
        "ɝʤ": "double_ers_dzh",
        "ɑrʤ": "double_ar_dzh",
        "ɛrʤ": "double_er_dzh",
        "ɪrʤ": "double_ir_dzh",
        "ɔrʤ": "double_or_dzh",
        "if": "double_i_f",
        "ɪf": "double_is_f",
        "eɪf": "double_ei_f",
        "ɛf": "double_e_f",
        "æf": "double_ae_f",
        "ɑf": "double_a_f",
        "ɔf": "double_c_f",
        "oʊf": "double_ou_f",
        "ʊf": "double_us_f",
        "uf": "double_u_f",
        "ʌf": "double_vu_f",
        "aɪf": "double_ai_f",
        "aʊf": "double_au_f",
        "ɔɪf": "double_oi_f",
        "ɝf": "double_ers_f",
        "ɑrf": "double_ar_f",
        "ɛrf": "double_er_f",
        "ɪrf": "double_ir_f",
        "ɔrf": "double_or_f",
        "iv": "double_i_v",
        "ɪv": "double_is_v",
        "eɪv": "double_ei_v",
        "ɛv": "double_e_v",
        "æv": "double_ae_v",
        "ɑv": "double_a_v",
        "ɔv": "double_c_v",
        "oʊv": "double_ou_v",
        "ʊv": "double_us_v",
        "uv": "double_u_v",
        "ʌv": "double_vu_v",
        "aɪv": "double_ai_v",
        "aʊv": "double_au_v",
        "ɔɪv": "double_oi_v",
        "ɝv": "double_ers_v",
        "ɑrv": "double_ar_v",
        "ɛrv": "double_er_v",
        "ɪrv": "double_ir_v",
        "ɔrv": "double_or_v",
        "iθ": "double_i_th",
        "ɪθ": "double_is_th",
        "eɪθ": "double_ei_th",
        "ɛθ": "double_e_th",
        "æθ": "double_ae_th",
        "ɑθ": "double_a_th",
        "ɔθ": "double_c_th",
        "oʊθ": "double_ou_th",
        "ʊθ": "double_us_th",
        "uθ": "double_u_th",
        "ʌθ": "double_vu_th",
        "aɪθ": "double_ai_th",
        "aʊθ": "double_au_th",
        "ɔɪθ": "double_oi_th",
        "ɝθ": "double_ers_th",
        "ɑrθ": "double_ar_th",
        "ɛrθ": "double_er_th",
        "ɪrθ": "double_ir_th",
        "ɔrθ": "double_or_th",
        "ið": "double_i_thv",
        "ɪð": "double_is_thv",
        "eɪð": "double_ei_thv",
        "ɛð": "double_e_thv",
        "æð": "double_ae_thv",
        "ɑð": "double_a_thv",
        "ɔð": "double_c_thv",
        "oʊð": "double_ou_thv",
        "ʊð": "double_us_thv",
        "uð": "double_u_thv",
        "ʌð": "double_vu_thv",
        "aɪð": "double_ai_thv",
        "aʊð": "double_au_thv",
        "ɔɪð": "double_oi_thv",
        "ɝð": "double_ers_thv",
        "ɑrð": "double_ar_thv",
        "ɛrð": "double_er_thv",
        "ɪrð": "double_ir_thv",
        "ɔrð": "double_or_thv",
        "is": "double_i_s",
        "ɪs": "double_is_s",
        "eɪs": "double_ei_s",
        "ɛs": "double_e_s",
        "æs": "double_ae_s",
        "ɑs": "double_a_s",
        "ɔs": "double_c_s",
        "oʊs": "double_ou_s",
        "ʊs": "double_us_s",
        "us": "double_u_s",
        "ʌs": "double_vu_s",
        "aɪs": "double_ai_s",
        "aʊs": "double_au_s",
        "ɔɪs": "double_oi_s",
        "ɝs": "double_ers_s",
        "ɑrs": "double_ar_s",
        "ɛrs": "double_er_s",
        "ɪrs": "double_ir_s",
        "ɔrs": "double_or_s",
        "iz": "double_i_z",
        "ɪz": "double_is_z",
        "eɪz": "double_ei_z",
        "ɛz": "double_e_z",
        "æz": "double_ae_z",
        "ɑz": "double_a_z",
        "ɔz": "double_c_z",
        "oʊz": "double_ou_z",
        "ʊz": "double_us_z",
        "uz": "double_u_z",
        "ʌz": "double_vu_z",
        "aɪz": "double_ai_z",
        "aʊz": "double_au_z",
        "ɔɪz": "double_oi_z",
        "ɝz": "double_ers_z",
        "ɑrz": "double_ar_z",
        "ɛrz": "double_er_z",
        "ɪrz": "double_ir_z",
        "ɔrz": "double_or_z",
        "iʃ": "double_i_sh",
        "ɪʃ": "double_is_sh",
        "eɪʃ": "double_ei_sh",
        "ɛʃ": "double_e_sh",
        "æʃ": "double_ae_sh",
        "ɑʃ": "double_a_sh",
        "ɔʃ": "double_c_sh",
        "oʊʃ": "double_ou_sh",
        "ʊʃ": "double_us_sh",
        "uʃ": "double_u_sh",
        "ʌʃ": "double_vu_sh",
        "aɪʃ": "double_ai_sh",
        "aʊʃ": "double_au_sh",
        "ɔɪʃ": "double_oi_sh",
        "ɝʃ": "double_ers_sh",
        "ɑrʃ": "double_ar_sh",
        "ɛrʃ": "double_er_sh",
        "ɪrʃ": "double_ir_sh",
        "ɔrʃ": "double_or_sh",
        "iʒ": "double_i_zh",
        "ɪʒ": "double_is_zh",
        "eɪʒ": "double_ei_zh",
        "ɛʒ": "double_e_zh",
        "æʒ": "double_ae_zh",
        "ɑʒ": "double_a_zh",
        "ɔʒ": "double_c_zh",
        "oʊʒ": "double_ou_zh",
        "ʊʒ": "double_us_zh",
        "uʒ": "double_u_zh",
        "ʌʒ": "double_vu_zh",
        "aɪʒ": "double_ai_zh",
        "aʊʒ": "double_au_zh",
        "ɔɪʒ": "double_oi_zh",
        "ɝʒ": "double_ers_zh",
        "ɑrʒ": "double_ar_zh",
        "ɛrʒ": "double_er_zh",
        "ɪrʒ": "double_ir_zh",
        "ɔrʒ": "double_or_zh",
        "im": "double_i_m",
        "ɪm": "double_is_m",
        "eɪm": "double_ei_m",
        "ɛm": "double_e_m",
        "æm": "double_ae_m",
        "ɑm": "double_a_m",
        "ɔm": "double_c_m",
        "oʊm": "double_ou_m",
        "ʊm": "double_us_m",
        "um": "double_u_m",
        "ʌm": "double_vu_m",
        "aɪm": "double_ai_m",
        "aʊm": "double_au_m",
        "ɔɪm": "double_oi_m",
        "ɝm": "double_ers_m",
        "ɑrm": "double_ar_m",
        "ɛrm": "double_er_m",
        "ɪrm": "double_ir_m",
        "ɔrm": "double_or_m",
        "in": "double_i_n",
        "ɪn": "double_is_n",
        "eɪn": "double_ei_n",
        "ɛn": "double_e_n",
        "æn": "double_ae_n",
        "ɑn": "double_a_n",
        "ɔn": "double_c_n",
        "oʊn": "double_ou_n",
        "ʊn": "double_us_n",
        "un": "double_u_n",
        "ʌn": "double_vu_n",
        "aɪn": "double_ai_n",
        "aʊn": "double_au_n",
        "ɔɪn": "double_oi_n",
        "ɝn": "double_ers_n",
        "ɑrn": "double_ar_n",
        "ɛrn": "double_er_n",
        "ɪrn": "double_ir_n",
        "ɔrn": "double_or_n",
        "iŋ": "double_i_ng",
        "ɪŋ": "double_is_ng",
        "eɪŋ": "double_ei_ng",
        "ɛŋ": "double_e_ng",
        "æŋ": "double_ae_ng",
        "ɑŋ": "double_a_ng",
        "ɔŋ": "double_c_ng",
        "oʊŋ": "double_ou_ng",
        "ʊŋ": "double_us_ng",
        "uŋ": "double_u_ng",
        "ʌŋ": "double_vu_ng",
        "aɪŋ": "double_ai_ng",
        "aʊŋ": "double_au_ng",
        "ɔɪŋ": "double_oi_ng",
        "ɝŋ": "double_ers_ng",
        "ɑrŋ": "double_ar_ng",
        "ɛrŋ": "double_er_ng",
        "ɪrŋ": "double_ir_ng",
        "ɔrŋ": "double_or_ng",
        "il": "double_i_l",
        "ɪl": "double_is_l",
        "eɪl": "double_ei_l",
        "ɛl": "double_e_l",
        "æl": "double_ae_l",
        "ɑl": "double_a_l",
        "ɔl": "double_c_l",
        "oʊl": "double_ou_l",
        "ʊl": "double_us_l",
        "ul": "double_u_l",
        "ʌl": "double_vu_l",
        "aɪl": "double_ai_l",
        "aʊl": "double_au_l",
        "ɔɪl": "double_oi_l",
        "ɝl": "double_ers_l",
        "ɑrl": "double_ar_l",
        "ɛrl": "double_er_l",
        "ɪrl": "double_ir_l",
        "ɔrl": "double_or_l"
    ]
    
    private static let specialSoundMap = [
        "iʔ": "double_i_glottal",
        "ɪʔ": "double_is_glottal",
        "eɪʔ": "double_ei_glottal",
        "ɛʔ": "double_e_glottal",
        "æʔ": "double_ae_glottal",
        "ɑʔ": "double_a_glottal",
        "ɔʔ": "double_c_glottal",
        "oʊʔ": "double_ou_glottal",
        "ʊʔ": "double_us_glottal",
        "uʔ": "double_u_glottal",
        "ʌʔ": "double_vu_glottal",
        "aɪʔ": "double_ai_glottal",
        "aʊʔ": "double_au_glottal",
        "ɔɪʔ": "double_oi_glottal",
        "ɝʔ": "double_ers_glottal",
        "ɑrʔ": "double_ar_glottal",
        "ɛrʔ": "double_er_glottal",
        "ɪrʔ": "double_ir_glottal",
        "ɔrʔ": "double_or_glottal",
        "ˈiɾə": "double_i_flap_shwua",
        "ˈɪɾə": "double_is_flap_shwua",
        "ˈeɪɾə": "double_ei_flap_shwua",
        "ˈɛɾə": "double_e_flap_shwua",
        "ˈæɾə": "double_ae_flap_shwua",
        "ˈɑɾə": "double_a_flap_shwua",
        "ˈɔɾə": "double_c_flap_shwua",
        "ˈoʊɾə": "double_ou_flap_shwua",
        "ˈʊɾə": "double_us_flap_shwua",
        "ˈuɾə": "double_u_flap_shwua",
        "ˈʌɾə": "double_vu_flap_shwua",
        "ˈaɪɾə": "double_ai_flap_shwua",
        "ˈaʊɾə": "double_au_flap_shwua",
        "ˈɔɪɾə": "double_oi_flap_shwua",
        "ˈɝɾə": "double_ers_flap_shwua",
        "ˈɑrɾə": "double_ar_flap_shwua",
        "ˈɛrɾə": "double_er_flap_shwua",
        "ˈɪrɾə": "double_ir_flap_shwua",
        "ˈɔrɾə": "double_or_flap_shwua",
        "pə": "double_p_shwua",
        "tə": "double_t_shwua",
        "kə": "double_k_shwua",
        "ʧə": "double_ch_shwua",
        "fə": "double_f_shwua",
        "θə": "double_th_shwua",
        "sə": "double_s_shwua",
        "ʃə": "double_sh_shwua",
        "bə": "double_b_shwua",
        "də": "double_d_shwua",
        "gə": "double_g_shwua",
        "ʤə": "double_dzh_shwua",
        "və": "double_v_shwua",
        "ðə": "double_thv_shwua",
        "zə": "double_z_shwua",
        "ʒə": "double_zh_shwua",
        "mə": "double_m_shwua",
        "nə": "double_n_shwua",
        "lə": "double_l_shwua",
        "wə": "double_w_shwua",
        "jə": "double_j_shwua",
        "hə": "double_h_shwua",
        "rə": "double_r_shwua",
        "əp": "double_shwua_p",
        "ət": "double_shwua_t",
        "ək": "double_shwua_k",
        "əʧ": "double_shwua_ch",
        "əf": "double_shwua_f",
        "əθ": "double_shwua_th",
        "əs": "double_shwua_s",
        "əʃ": "double_shwua_sh",
        "əb": "double_shwua_b",
        "əd": "double_shwua_d",
        "əg": "double_shwua_g",
        "əʤ": "double_shwua_dzh",
        "əv": "double_shwua_v",
        "əð": "double_shwua_thv",
        "əz": "double_shwua_z",
        "əʒ": "double_shwua_zh",
        "əm": "double_shwua_m",
        "ən": "double_shwua_n",
        "əŋ": "double_shwua_ng",
        "əl": "double_shwua_l",
        "pɚ": "double_p_eru",
        "tɚ": "double_t_eru",
        "kɚ": "double_k_eru",
        "ʧɚ": "double_ch_eru",
        "fɚ": "double_f_eru",
        "θɚ": "double_th_eru",
        "sɚ": "double_s_eru",
        "ʃɚ": "double_sh_eru",
        "bɚ": "double_b_eru",
        "dɚ": "double_d_eru",
        "gɚ": "double_g_eru",
        "ʤɚ": "double_dzh_eru",
        "vɚ": "double_v_eru",
        "ðɚ": "double_thv_eru",
        "zɚ": "double_z_eru",
        "ʒɚ": "double_zh_eru",
        "mɚ": "double_m_eru",
        "nɚ": "double_n_eru",
        "lɚ": "double_l_eru",
        "wɚ": "double_w_eru",
        "jɚ": "double_j_eru",
        "hɚ": "double_h_eru",
        "rɚ": "double_r_eru",
        "ɚp": "double_eru_p",
        "ɚt": "double_eru_t",
        "ɚk": "double_eru_k",
        "ɚʧ": "double_eru_ch",
        "ɚf": "double_eru_f",
        "ɚθ": "double_eru_th",
        "ɚs": "double_eru_s",
        "ɚʃ": "double_eru_sh",
        "ɚb": "double_eru_b",
        "ɚd": "double_eru_d",
        "ɚg": "double_eru_g",
        "ɚʤ": "double_eru_dzh",
        "ɚv": "double_eru_v",
        "ɚð": "double_eru_thv",
        "ɚz": "double_eru_z",
        "ɚʒ": "double_eru_zh",
        "ɚm": "double_eru_m",
        "ɚn": "double_eru_n",
        "ɚŋ": "double_eru_ng",
        "ɚl": "double_eru_l",
        ]
}
